name: Docker

on:
  push:
    branches: [main]
  pull_request:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: docker/setup-buildx-action@v3
      - name: Build image
        run: |
          IMAGE=ghcr.io/${{ github.repository_owner }}/sheetbridge:latest
          docker build -t "$IMAGE" .
      - name: Compose smoke
        run: |
          docker compose version || echo "compose plugin not present, skipping"
          if docker compose version >/dev/null 2>&1; then
            echo -e "GOOGLE_SHEET_ID=test\nAPI_KEYS=ci_key" > .env
            docker compose up -d
            sleep 5
            curl -f -H "X-API-Key: ci_key" http://localhost:8000/health
            docker compose down -v
          fi
